### ISSUE TITLE
Gem::RemoteFetcher::FetchError: Received fatal alert: bad_record_mac

### ISSUE THREAD

**Issue by keaplogik** [NUBIC/ladle#26]
If you do a bundle install on ladle using JRuby you may run into an error `Gem::RemoteFetcher::FetchError: Received fatal alert: bad_record_mac`

**Comment by keaplogik** [comment]
This is relates to Java Version less than Java 1.7.0_51 b04 and is fixed for future releases. Wanted to document it here that this occurred. Similar issue with logstash found [here](https://github.com/elastic/logstash/issues/2537).

**Comment by rsutphin** [comment]
Thanks, @keaplogik.
