### ISSUE TITLE
Server stops after succesfull start

### ISSUE THREAD

**Issue by encorex** [NUBIC/ladle#28]
Hi there, 
i need ladle to simulate a test server everything works ok, but my ldap server stops after a few seconds here the lig

ApacheDS: INFO: Successful bind of an LDAP Service (3897) is completed.
ApacheDS: INFO: Ldap service started.
- Stopped waiting after 9.034545 seconds
- Server started successfully
Stopping server on 3897
- Stopping server process
- Signalling server process to stop if not already stopped
ApacheDS: INFO: clearing all the caches

**Comment by r0qs** [comment]
Hi @encorex, I recently had a problem similar to yours. Apparently this problem is related to how the tmpdir parameter is set on ladle, that does not work as expected on some OS (I test on a docker that runs CentOS).

When I use the default value (/tmp) the service not starts properly and got a timeout.
```
      Ladle::Server.new(
        quiet: false,
        verbose: true
      )
```

I omitted some outputs that are not relevant:
```
LDAPProvider
Starting server on 3897
- Started subprocess 143
- Waiting for server to start
  . waited 0.000155335 seconds
  . waited 0.500505033 seconds
  . waited 1.00085712 seconds
 ....
  . waited 57.052111676 seconds
  . waited 57.552460414 seconds
  . waited 58.052877863 seconds
  . waited 58.553225584 seconds
  . waited 59.053589491 seconds
  . waited 59.553958917 seconds
- Stopped waiting after 60.054328508 seconds
Stopping server on 3897
- Stopping server process
- Signalling server process to stop if not already stopped
ApacheDS: INFO: fetching the cache named groupCache
ApacheDS: INFO: Initializing ...
ApacheDS: INFO: Initialization complete.
ApacheDS: INFO: clearing all the caches
! Timed out
```
This make my tests fail because ladle died prematurely. But if I pass another path in tmpdir and try again, for example:
```
      Ladle::Server.new(
        quiet: false,
        verbose: true,
        tmpdir: '/home/application/ladle'
      )
```
The service starts and works as expected. I don't know why, but I hope it helps you.

```
LDAPProvider
Starting server on 3897
- Started subprocess 275
- Waiting for server to start
  . waited 0.000498383 seconds
  . waited 0.500954104 seconds
  ...
  . waited 20.026135931 seconds
  . waited 20.526513458 seconds
  . waited 21.026879563 seconds
  . waited 21.527243414 seconds
  . waited 22.027586623 seconds
ApacheDS: INFO: Successful bind of an LDAP Service (3897) is completed.
ApacheDS: INFO: Ldap service started.
- Stopped waiting after 53.054445786 seconds
- Server started successfully
  Authentication
    successfully authenticates a user with correct credentials
Stopping server on 3897
- Stopping server process
- Signalling server process to stop if not already stopped
ApacheDS: INFO: clearing all the caches
```

**Comment by encorex** [comment]
Thanks for your help !
